---
#listen_on: 127.0.0.1:9992
listen_on: 0.0.0.0:9992
services:
  sentinelhub:
    lease_timeout_secs: 10
    credentials:
      - user: user_a
        password: secret_a
        num_concurrent: 2
      - user: user_b
        password: secret_b

access_tokens:
  - test_token

# optional ssl support. remove the ssl-section to disable
#
# to create a self-signed temporary cert for testing:
# `openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 365 -subj '/CN=localhost'`
ssl:
  private_key_pem_file: key.pem
  certificate_chain_file: cert.pem