---
#listen_on: 127.0.0.1:9992
listen_on: 0.0.0.0:9992
services:
  sentinelhub:
    lease_timeout_secs: 10
    credentials:
      - user: user_a
        password: secret_a
        num_concurrent: 2
      - user: user_b
        password: secret_b

access_tokens:
  - test_token